-- basics
require "settings"
require "keymaps"
-- plugins
require "plugins.cmp"
require "plugins.lsp"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.gitsigns"
require "plugins.nvim-tree"
require "plugins.bufferline"
require "plugins.lualine"
require "plugins.impatient"
require "plugins.indentline"
require "plugins.autocommands"
require 'plugins.markdownpreview'