[font]
size = 14

[font.bold]
family = "Monaco Nerd Font"

[font.bold_italic]
family = "Monaco Nerd Font"

[font.italic]
family = "Monaco Nerd Font"

[font.normal]
family = "Monaco Nerd Font"

[cursor]
blink_interval = 750
thickness = 0.2
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty"

[scrolling]
multiplier = 0

[window]
opacity = 0.9
startup_mode = "Windowed"
decorations = "Buttonless"
# Window startup position
position = "None"  # Default: "None"
padding = { x = 0, y = 0 }  # Default: x = 0, y = 0

[window.dimensions]
columns = 189
lines = 50

[[keyboard.bindings]]
chars = "\u0006v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006h"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006t"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00060"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "{"
key = 28
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 25
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 26
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "|"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 23
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 22
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006\u001B[C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006\u001B[A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006\u001B[B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[D"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[C"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[A"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[B"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006p"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0006n"
key = "Right"
mods = "Control"

[shell]
args = ["--login", "-c", "tmux-wrapper attach || tmux-wrapper; gpg-connect-agent-wrapper reloadagent /bye"]
program = "/bin/zsh"


# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]

background = "#282a36"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"

[colors.cursor]

text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a"

[colors.normal]

black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]

black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]

foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]

background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]

foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#282a36"

