windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAGQAABZ8AAANUAAAAAAAAADUAAAWfAAADVAAAAAACAAAABaAAAAAAAAAA
    NQAABZ8AAANU
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2022-04-25T12:18:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: .dotfiles/setup_macbook.md at main · alexchaichan/.dotfiles
      url: https://github.com/alexchaichan/.dotfiles/blob/main/setup/setup_macbook.md
      zoom: 1.0
