#!/usr/bin/env zsh

# check for os type
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     os=linux;;
    Darwin*)    os=osx;;
    CYGWIN*)    os=cygwin;;
    MINGW*)     os=mingw;;
    *)          os="UNKNOWN:${unameOut}"
esac

# create $ directories
if [[ "$os" == "osx" || "$os" == "linux" ]]; then
  export HOME="$(echo -n $(bash -c "cd ~${USER} && pwd"))"
fi
export DOTFILES=$HOME/.dotfiles

# define connected keyboards

if [[ "$os" == "osx" ]]; then

  # keychron k2
  export KEYCHRON_USB=$(ioreg -p IOUSB -w0 | sed 's/[^o]*o //; s/@.*$//' | grep "Keychron" | sed 's/[^a-zA-Z0-9]//g')
  export KEYCHRON_BLUETOOTH=$(system_profiler SPBluetoothDataType | grep "0x800020")

  #

elif [[ "$os" == "linux" ]]; then

  # keychron k2
  export KEYCHRON_USB=$(lsusb | grep 'Keychron' | cut -f7 -d" ")
  export KEYCHRON_BLUETOOTH=$()

  #

fi

# specific Keyboard settings osx

  # keychron k2
if [[ "$os" == "osx" && "$KEYCHRON_USB" == "KeychronK2" || "$KEYCHRON_BLUETOOTH" == "              Services: 0x800020 < HID ACL >" ]]; then

  xkbswitch -s 2

  /usr/bin/hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x700000029}, {"HIDKeyboardModifierMappingSrc":0x70000001D, "HIDKeyboardModifierMappingDst":0x70000001C}, {"HIDKeyboardModifierMappingSrc":0x70000001C, "HIDKeyboardModifierMappingDst":0x70000001D}]}' >/dev/null 2>&1

  #

#elif [[ "$os" == "osx" && "$_BLUETOOTH" == "" || "$_BLUETOOTH" == ""]]; then

else

  xkbswitch -s 1

  /usr/bin/hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x700000029}]}' >/dev/null 2>&1

fi
