#!/bin/bash

if [ -x /usr/local/bin/pass ]; then
    exec /usr/local/bin/pass "$@"
elif [ -x /usr/bin/pass ]; then
    exec /usr/bin/pass "$@"
elif [ -x /opt/homebrew/bin/pass ]; then
    exec /opt/homebrew/bin/pass "$@"
else
    echo "pass not found" >&2
    exit 1
fi