#!/bin/bash

# Define the base directory of your dotfiles
DOTFILES_DIR="$(pwd)/HOME"

# Iterate over all files in your dotfiles directory
find "$DOTFILES_DIR" -type f | while read -r file; do
  # Determine the relative path of the file from the dotfiles directory
  rel_path="${file#$DOTFILES_DIR/}"

  # Create the destination directory if it does not exist
  dest_dir="$HOME/$(dirname "$rel_path")"
  mkdir -p "$dest_dir"

  # Create the symbolic link
  ln -sf "$file" "$HOME/$rel_path"

done
