#!/bin/bash

if [ -x /usr/local/bin/tmux ]; then
    exec /usr/local/bin/tmux "$@"
elif [ -x /usr/bin/tmux ]; then
    exec /usr/bin/tmux "$@"
elif [ -x /opt/homebrew/bin/tmux ]; then
    exec /opt/homebrew/bin/tmux "$@"
else
    echo "tmux not found" >&2
    exit 1
fi